### ISSUE TITLE
UI Mockup - Missing Offline Mode?

### ISSUE THREAD

**Issue by vamaraju** [CMPUT301F15T01/YesWeCandroid#2]
The UI mockup might be missing layouts for the offline-mode screens. Not sure if there would be any separate screens for that; maybe just a popup to state that the user is currently offline?

**Comment by theWhyteRabbit** [comment]
I'll bring it up at the meeting today.

**Comment by theWhyteRabbit** [comment]
for now, screens in offline mode will be the same as the screens in online mode.

**Comment by vamaraju** [comment]
Sounds good. I'm closing this issue.
